apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-deploy
  name: api-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 31534
  selector:
    app: api-deploy
status:
  loadBalancer: {}
