apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-deploy
  name: db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db-deploy
status:
  loadBalancer: {}
