apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: seeder-deply
  name: seeder-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder-deply
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seeder-deply
    spec:
      containers:
      - image: seeder
        name: seeder
        imagePullPolicy: Never # Use private image
        resources: {}
        env:
        - name: MYSQL_PASSWORD
          value: Admin123 # Todo use secret
        - name: MYSQL_HOST
          value: db-service
        - name: MYSQL_USER
          value: monty
        - name: MYSQL_DB
          value: 1000_cows
status: {}
